### ISSUE TITLE
Need Way to Identify Zone based on sender and recipient addres  for UPS

### ISSUE THREAD

**Issue by kishanapex** [ShipEngine/shipengine-dotnet#106]
I am integrating UPS API for Shipengine. In my programming i have to charge to client based on Zone provided by UPS. I need some API by which i know Zone from sender and recipient address. I know UPS is giving option to download file which give zone details from link https://www.ups.com/us/en/support/shipping-support/shipping-costs-rates/retail-rates.page. But if i have to integrate all zones of US then i have to download more then 900 files. Is any option to get list of zones though any API or though any download option.

**Comment by AnneOReilly** [comment]
Hey @kishanapex , we don't have these available via API but I've got a list of the current UPS zones with to/from zip-3s here for you so you don't have to download 900 different files.  Hope this helps!

[ups_zonemap.csv](https://github.com/user-attachments/files/16349518/ups_zonemap.csv)

**Comment by kishanapex** [comment]
Really grateful for this information. UPS also having different zones for different shipping method for Hawaii, Alaska, do you able to help in that which give me list of source zip, destination zip , shipping method and zone

**Comment by AnneOReilly** [comment]
@kishanapex unfortunately I don't have service level UPS zone information

**Comment by kishanapex** [comment]
do you have zone information for Alaska and Hawaii for UPS

**Comment by kishanapex** [comment]
do you have any update on my last question? do you have zone information for Alaska and Hawaii for UPS
