### ISSUE TITLE
Unable to designate Third Party billing

### ISSUE THREAD

**Issue by dianecawley** [ShipEngine/shipengine-dotnet#113]
I'm using the C# SDK nuget package 2.3.2

When I ship a package using production API key, and set the advanced options as shown below, I get an error message back from the API call stating:   A shipping carrier error occurred: The shipper cannot use the provided UPS account number as the payment method.

I have tried this with multiple UPS accounts and continue to get this error.

I am in need of help to understand why this message is occuring.
Thank you,

I am setting up the Advanced options as follows:  

AdvancedShipmentOptions advoptions = new AdvancedShipmentOptions();
                if (BoxData.FreightTerms == "3P")
                {
                    advoptions.BillToAccount = "HW1377";
                    advoptions.BillToCountryCode = "US";
                    advoptions.BillToParty = BillToParty.ThirdParty;
                    advoptions.BillToPostalCode = "23005";                   
                }

And here is the call to create the label..
.
                var rateParams = new ShipEngineSDK.CreateLabelFromShipmentDetails.Params()
                {
                    LabelDownloadType = LabelDownloadType.Url,
                    LabelFormat = LabelFormat.ZPL,
                    LabelLayout = LabelLayout.FourBySix,
                    IsReturnLabel = false,
                    Shipment = new ShipEngineSDK.CreateLabelFromShipmentDetails.Shipment()
                    {
                        CarrierId = SelectedCarrierID,
                        ServiceCode = DelType,
                        ShipFrom = new Address()
                        {
                            Name = "Shipping Dept",
                            AddressLine1 = BoxData.CompanyAddr1,
                            CityLocality = BoxData.CompanyCity,
                            StateProvince = BoxData.CompanyState,
                            PostalCode = BoxData.CompanyZip,
                            CountryCode = Country.US,
                            Phone = BoxData.CompanyPhone
                        },
                        ShipTo = new Address()
                        {
                            Name = BoxData.ShipName,
                            AddressLine1 = BoxData.ShipAddr1,
                            AddressLine2 = BoxData.ShipAddr2,
                            CityLocality = BoxData.ShipCity,
                            StateProvince = BoxData.ShipState,
                            PostalCode = BoxData.ShipZip,
                            CountryCode = Country.US,
                            Phone = "512-555-5555"
                        },
                        Packages = new List<Package>()
                        {
                            new Package() {
                                Weight = new Weight() {
                                    Value = BoxData.ActWeight,
                                    Unit = WeightUnit.Pound
                                },
                                Dimensions = new Dimensions() {
                                    Length = BoxLength,
                                    Width = BoxWidth,
                                    Height = BoxHeight,
                                    Unit = DimensionUnit.Inch,
                                }
                            }
                        },
                        AdvancedOptions = advoptions,
                        Confirmation = (DeliveryConfirmation)ConfirmationType
                    }
                };

**Comment by AnneOReilly** [comment]
Hey @dianecawley !  Thanks for your question.  Since this isn't an issue specific to the SDK, can you please create a ticket with support@shipengine.com?  The team there will be able to provide context on this type of error from UPS.

**Comment by dianecawley** [comment]
I tried to create a ticket with support and they directed me to the dev team.
But I will pass this along in another ticket to see what happens.



Diane Cawley, MBA

Chief Software Architect

Savant Software, Inc.

(623) 223-1517 (Direct dial)

(602) 906-3047 x1517 (switchboard)

(602) 721-5072 (mobile)



Please consider the environment before printing this e-mail
CONFIDENTIALITY NOTICE

UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW [Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)]

________________________________
