### ISSUE TITLE
Error serializing result when address message detail code is null.

### ISSUE THREAD

**Issue by kirkbrauer** [ShipEngine/shipengine-dotnet#42]
I have been attempting to validate an address using the .NET SDK, however when the detail_code field of an address validation message is null, I get the following exception:

Error converting value {null} to type 'ShipEngineSDK.ValidateAddresses.ValidationMessageDetailCode'

Most likely, the detail_code is not marked as nullable in the schema, and this breaks the validation deserialization.

**Comment by pierce-h** [comment]
@kirkbrauer thank you for reporting this issue.

**Comment by sushithegreat** [comment]
Fixed in 1.0.3
