### ISSUE TITLE
Customs Quantity for International Shipping

### ISSUE THREAD

**Issue by cdesvarieux** [ShipEngine/shipengine-dotnet#49]
receiving the following error: request.shipment.customs.customs_items[0].quantity: Input string '5.0' is not a valid integer. Path 'shipment.customs.customs_items[0].quantity', line 1, position 717. The API has this field defined as an Integer while the SDK has it defined as a double. 

ShipEngineSDK.CreateLabelFromShipmentDetails.Params.Shipment.Customs.Customs_Items[].Quantity

**Comment by AnneOReilly** [comment]
Thank you for this report! We will queue this for resolution in the next release.

**Comment by awveracore** [comment]
Can you please give us an idea of next expected release date? Thx

**Comment by cdesvarieux** [comment]
We were trying to get this out by Tuesday September 20, 2022.

**Comment by awveracore** [comment]
Thank you!

**Comment by as206em** [comment]
I'm still getting the same exact issue with the custom item
I'm using 1.1.0 version

**Comment by lanthonyneville** [comment]
You fixed the type of CustomsItem.Quantity, but the same issue exists with ShipmentItem.Quantity - it is defined as an Integer in the API while the SDK has it defined as a double

![image](https://github.com/ShipEngine/shipengine-dotnet/assets/22200046/fe68279d-d86e-4c71-a7e1-9c5aad88b2dd)

**Comment by lanthonyneville** [comment]
Actually, there are two classes called CustomsItem ... one has the correct int type for Quantity and one is double.
