### ISSUE TITLE
Outdated Nuget and .NET

### ISSUE THREAD

**Issue by Tal-Owl** [ShipEngine/shipengine-dotnet#78]
I downloaded the C# SDK and noticed it has several Nuget packages that are outdated and have reported vulnerabilities. 

Also, the .NET target version is out of support. Is it ok to upgrade these and still use the SDK?

I am reviewing your services and process approximately 10,000 labels a month.

See image below, I use Visual Studio 2022 with the latest .Net framework.

<img width="560" alt="ShipEngine1" src="https://github.com/ShipEngine/shipengine-dotnet/assets/165179297/167b7d3a-5a18-4303-a2c2-af8fea2d14dc">

**Comment by AnneOReilly** [comment]
Hey there,

You should be alright to upgrade the version.  [Microsoft has stated](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0) that versions 5 and later will continue to support older .Net standard versions.

We have a major version update planned for later this year that will address the out of support Nuget packages.

**Comment by AnneOReilly** [comment]
@Tal-Owl We've got the major version update out, with updated frameworks.  Check out 2.0.0!
