### ISSUE TITLE
Axios ERR_NETWORK

### ISSUE THREAD

**Issue by remzioten** [ShipEngine/shipengine-dotnet#87]
Hi 
I am using React with Axios to communicate with ShipEngine API. It keeps giving AxiosError, code 'ERR_NETWORK'. 
I have no issue when using Postman. I have no issue communication with ShipStation API. Not sure the reason for this issue. Any help will be appreciated.

**Comment by remzioten** [comment]
Hey @AnneOReilly - Thanks. That was the problem. I was calling from a browser. 
If I am building a JS app to use locally, what do you suggest to use to overcome this?

**Comment by AnneOReilly** [comment]
@remzioten It depends a little bit on your usecase.  If you are setting up ShipEngine to use with a single company, we suggest using a proxy server to field calls from the browser and then pass them on with proper auth to ShipEngine.  We strongly advise not sending the API key directly from the browser.

If you're building an app for a platform that would allow multiple companies to ship, we have some pre-built embeddable web components you could leverage: https://www.shipengine.com/elements/
